// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9QLCU3h0uTLXaJHoYL6nUQB3AhD-ZuI',
    appId: '1:776570216110:web:704ea6b524216cd75d173f',
    messagingSenderId: '776570216110',
    projectId: 'codigo-task-66a3e',
    authDomain: 'codigo-task-66a3e.firebaseapp.com',
    storageBucket: 'codigo-task-66a3e.appspot.com',
    measurementId: 'G-DESJDMSJ1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPoypyIJrU8Tr2VrP5VZTnLt-ABGw4h1g',
    appId: '1:776570216110:android:98cf2a77405c1ac45d173f',
    messagingSenderId: '776570216110',
    projectId: 'codigo-task-66a3e',
    storageBucket: 'codigo-task-66a3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPI4deRZtcFc-FOPWIW3J9Z6-EKakA3xU',
    appId: '1:776570216110:ios:740edd2212c51ab85d173f',
    messagingSenderId: '776570216110',
    projectId: 'codigo-task-66a3e',
    storageBucket: 'codigo-task-66a3e.appspot.com',
    iosBundleId: 'com.example.flutterCodigoFiretask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPI4deRZtcFc-FOPWIW3J9Z6-EKakA3xU',
    appId: '1:776570216110:ios:740edd2212c51ab85d173f',
    messagingSenderId: '776570216110',
    projectId: 'codigo-task-66a3e',
    storageBucket: 'codigo-task-66a3e.appspot.com',
    iosBundleId: 'com.example.flutterCodigoFiretask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9QLCU3h0uTLXaJHoYL6nUQB3AhD-ZuI',
    appId: '1:776570216110:web:8aaee2dc5ec2b2e55d173f',
    messagingSenderId: '776570216110',
    projectId: 'codigo-task-66a3e',
    authDomain: 'codigo-task-66a3e.firebaseapp.com',
    storageBucket: 'codigo-task-66a3e.appspot.com',
    measurementId: 'G-VPEPBQHGJG',
  );
}
